# Generated by Django 5.1.3 on 2024-11-25 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_hospital', models.CharField(choices=[('abc', 'ABC Hospital'), ('pqr', 'PQR Hospital'), ('xyz', 'XYZ Hospital')], max_length=3)),
                ('employee_id', models.CharField(max_length=50)),
                ('name_of_employee', models.CharField(max_length=100)),
                ('designation_of_employee', models.CharField(max_length=100)),
                ('place_of_posting', models.CharField(max_length=100)),
                ('name_of_patient', models.CharField(max_length=100)),
                ('relationship_with_employee', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('name_of_doctor', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('treatment_type', models.CharField(choices=[('conservative', 'Conservative'), ('surgical', 'Surgical')], max_length=12)),
                ('medical_advance_required', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('doctors_prescription', models.FileField(upload_to='prescriptions/')),
                ('estimate', models.FileField(upload_to='estimates/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('document', models.FileField(upload_to='documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
